services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    working_dir: /app
    volumes:
      - ./frontend/test-results:/app/test-results
      - ./frontend/playwright-report:/app/playwright-report
    networks: [auth_starter_frontend_test]

networks:
  auth_starter_frontend_test:
    driver: bridge
